# 匯入資料及前處理

In [1]:
import pandas as pd
import numpy as np

# pd.set_option('precision', 0)
data = pd.read_csv('input.txt', sep="\t",header = None, error_bad_lines=False)

In [2]:
data = data.drop(columns = 0,axis = 1)

In [3]:
data

,1,2,3,4,5,6,7,8,9,10,...,123,124,125,126,127,128,129,130,131,132
0,11,166,11.0,4103.0,11.0,8715.0,24.0,4103.0,24.0,8715.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,66,2404,66.0,5954.0,66.0,6282.0,90.0,2404.0,90.0,5954.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,128,5132,128.0,9446.0,139.0,316.0,139.0,5132.0,139.0,6889.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,7182,162.0,8985.0,169.0,3710.0,169.0,4652.0,169.0,5069.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,188,649,188.0,1264.0,188.0,2181.0,188.0,6268.0,194.0,2181.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,894688,3638,894688.0,5868.0,894702.0,3638.0,894702.0,5868.0,894723.0,1767.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19996,894762,8480,894777.0,8480.0,894790.0,8480.0,894808.0,8480.0,894821.0,8480.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19997,894837,3268,894837.0,6149.0,894837.0,6624.0,894858.0,3268.0,894858.0,6149.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19998,894933,26,894933.0,9706.0,894947.0,26.0,894947.0,9706.0,894956.0,8007.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19999,894972,7357,894988.0,2046.0,894988.0,5756.0,894988.0,7357.0,894988.0,7467.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#將資料從dataframe轉為array
test = data.head(10)
test = test.values
test

array([[  11.,  166.,   11., ...,   nan,   nan,   nan],
       [  66., 2404.,   66., ...,   nan,   nan,   nan],
       [ 128., 5132.,  128., ...,   nan,   nan,   nan],
       ...,
       [ 318., 2701.,  318., ...,   nan,   nan,   nan],
       [ 391.,  316.,  391., ...,   nan,   nan,   nan],
       [ 513., 2695.,  517., ...,   nan,   nan,   nan]])

In [5]:
#將資料從array轉為二維list
import numpy as np
import math
news = []
for i in test:
    tmp = [x for x in i if math.isnan(x) == False]
    news.append(tmp)
new = []
for i in news:
    tmp = [int(x) for x in i if math.isnan(x) == False]
    new.append(tmp)
new

[[11,
  166,
  11,
  4103,
  11,
  8715,
  24,
  4103,
  24,
  8715,
  36,
  166,
  36,
  3704,
  36,
  6568,
  36,
  8375,
  36,
  8715,
  51,
  166,
  51,
  9406],
 [66,
  2404,
  66,
  5954,
  66,
  6282,
  90,
  2404,
  90,
  5954,
  90,
  6282,
  109,
  2404,
  109,
  3203],
 [128,
  5132,
  128,
  9446,
  139,
  316,
  139,
  5132,
  139,
  6889,
  139,
  7594,
  157,
  5132,
  157,
  7494],
 [162,
  7182,
  162,
  8985,
  169,
  3710,
  169,
  4652,
  169,
  5069,
  169,
  8985,
  176,
  5069,
  176,
  7182,
  176,
  9803,
  182,
  411,
  182,
  5069,
  182,
  6258,
  182,
  9803],
 [188,
  649,
  188,
  1264,
  188,
  2181,
  188,
  6268,
  194,
  2181,
  194,
  5127,
  194,
  5447,
  194,
  5493,
  194,
  7208,
  203,
  1264,
  203,
  1642,
  203,
  5264,
  203,
  5447,
  203,
  5493,
  203,
  6268,
  211,
  1264,
  211,
  5127,
  211,
  5264,
  211,
  6201,
  211,
  6268],
 [222,
  6549,
  222,
  7160,
  222,
  8480,
  228,
  6549,
  228,
  7160,
  228,
  8480,
  233,
  8220,
  233,
  8480],
 [248,
  4681,
  248,
  5112,
  248,
  8117,
  263,
  5112,
  263,
  6549,
  263,
  7165,
  263,
  8117,
  276,
  5112,
  276,
  7165,
  276,
  8117,
  276,
  9694,
  288,
  4681,
  288,
  5184,
  288,
  7165,
  288,
  9694,
  306,
  5112,
  306,
  8117],
 [318,
  2701,
  318,
  8007,
  325,
  815,
  325,
  3638,
  325,
  5419,
  333,
  2701,
  333,
  3638,
  342,
  552,
  342,
  4811,
  342,
  5419,
  350,
  815,
  357,
  552,
  357,
  815,
  357,
  4132,
  357,
  4811,
  357,
  5419,
  363,
  830,
  363,
  2701,
  363,
  3638,
  363,
  5419,
  374,
  552,
  374,
  3278,
  374,
  4132,
  374,
  4811],
 [391,
  316,
  391,
  3390,
  391,
  7594,
  391,
  8261,
  391,
  8447,
  411,
  731,
  411,
  3203,
  431,
  3203,
  431,
  6273,
  452,
  316,
  452,
  514,
  452,
  2681,
  452,
  5804,
  452,
  7594,
  469,
  1390,
  469,
  3390,
  469,
  5804,
  489,
  731,
  489,
  1782,
  489,
  3203,
  489,
  6273,
  503,
  316,
  503,
  3203,
  503,
  3390,
  503,
  5804,
  503,
  6515,
  503,
  7594,
  503,
  9874],
 [513, 2695, 517, 5060, 517, 9013]]

In [6]:
new_data=[] #取出資料欄位並創建新的list存放
for i in new:
    tmp=[]
    for j in range(2,len(i)+1,2):
        tmp.append(i[j-1])
    new_data.append(tmp)
new_data

[[166, 4103, 8715, 4103, 8715, 166, 3704, 6568, 8375, 8715, 166, 9406],
 [2404, 5954, 6282, 2404, 5954, 6282, 2404, 3203],
 [5132, 9446, 316, 5132, 6889, 7594, 5132, 7494],
 [7182, 8985, 3710, 4652, 5069, 8985, 5069, 7182, 9803, 411, 5069, 6258, 9803],
 [649,
  1264,
  2181,
  6268,
  2181,
  5127,
  5447,
  5493,
  7208,
  1264,
  1642,
  5264,
  5447,
  5493,
  6268,
  1264,
  5127,
  5264,
  6201,
  6268],
 [6549, 7160, 8480, 6549, 7160, 8480, 8220, 8480],
 [4681,
  5112,
  8117,
  5112,
  6549,
  7165,
  8117,
  5112,
  7165,
  8117,
  9694,
  4681,
  5184,
  7165,
  9694,
  5112,
  8117],
 [2701,
  8007,
  815,
  3638,
  5419,
  2701,
  3638,
  552,
  4811,
  5419,
  815,
  552,
  815,
  4132,
  4811,
  5419,
  830,
  2701,
  3638,
  5419,
  552,
  3278,
  4132,
  4811],
 [316,
  3390,
  7594,
  8261,
  8447,
  731,
  3203,
  3203,
  6273,
  316,
  514,
  2681,
  5804,
  7594,
  1390,
  3390,
  5804,
  731,
  1782,
  3203,
  6273,
  316,
  3203,
  3390,
  5804,
  6515,
  7594,
  9874],
 [2695, 5060, 9013]]

In [7]:
index = [] #建立list存放transaction time
for i in new:
    tmp=[]
    for j in range(0,len(i),2):
        tmp.append(i[j])
    index.append(tmp)
index

[[11, 11, 11, 24, 24, 36, 36, 36, 36, 36, 51, 51],
 [66, 66, 66, 90, 90, 90, 109, 109],
 [128, 128, 139, 139, 139, 139, 157, 157],
 [162, 162, 169, 169, 169, 169, 176, 176, 176, 182, 182, 182, 182],
 [188,
  188,
  188,
  188,
  194,
  194,
  194,
  194,
  194,
  203,
  203,
  203,
  203,
  203,
  203,
  211,
  211,
  211,
  211,
  211],
 [222, 222, 222, 228, 228, 228, 233, 233],
 [248,
  248,
  248,
  263,
  263,
  263,
  263,
  276,
  276,
  276,
  276,
  288,
  288,
  288,
  288,
  306,
  306],
 [318,
  318,
  325,
  325,
  325,
  333,
  333,
  342,
  342,
  342,
  350,
  357,
  357,
  357,
  357,
  357,
  363,
  363,
  363,
  363,
  374,
  374,
  374,
  374],
 [391,
  391,
  391,
  391,
  391,
  411,
  411,
  431,
  431,
  452,
  452,
  452,
  452,
  452,
  469,
  469,
  469,
  489,
  489,
  489,
  489,
  503,
  503,
  503,
  503,
  503,
  503,
  503],
 [513, 517, 517]]

# 計算次數用於資料前處理(把同時間之資料合併)

In [8]:
inits = [] #紀錄每一種資料
datas = []

for i in index:
    tmp = []
    for j in i:       # 1st loop
        if j not in tmp:   # 2nd loop
            tmp.append(j)
    datas.append(tmp)
for i in datas:
    for j in i:
        if(j not in inits):
            inits.append(j)
print(inits)

[11, 24, 36, 51, 66, 90, 109, 128, 139, 157, 162, 169, 176, 182, 188, 194, 203, 211, 222, 228, 233, 248, 263, 276, 288, 306, 318, 325, 333, 342, 350, 357, 363, 374, 391, 411, 431, 452, 469, 489, 503, 513, 517]

In [9]:
from collections import Counter #匯入一種dict的子類別 存放資料
p = Counter()
for i in inits:
    for d in index:
        for x in d:
            if(i == x):
                p[i]+=1
print("計算數量：") #每種資料個紀錄一次(出現次數)
for i in p:
    print(str([i])+": "+str(p[i])) #出現次數
print()

計算數量：
[11]: 3
[24]: 2
[36]: 5
[51]: 2
[66]: 3
[90]: 3
[109]: 2
[128]: 2
[139]: 4
[157]: 2
[162]: 2
[169]: 4
[176]: 3
[182]: 4
[188]: 4
[194]: 5
[203]: 6
[211]: 5
[222]: 3
[228]: 3
[233]: 2
[248]: 3
[263]: 4
[276]: 4
[288]: 4
[306]: 2
[318]: 2
[325]: 3
[333]: 2
[342]: 3
[350]: 1
[357]: 5
[363]: 4
[374]: 4
[391]: 5
[411]: 2
[431]: 2
[452]: 5
[469]: 3
[489]: 4
[503]: 7
[513]: 1
[517]: 2

In [10]:
new_new_data = []
for i in new_data:
    for j in i:
        new_new_data.append(j)
new_new_data

[166,
 4103,
 8715,
 4103,
 8715,
 166,
 3704,
 6568,
 8375,
 8715,
 166,
 9406,
 2404,
 5954,
 6282,
 2404,
 5954,
 6282,
 2404,
 3203,
 5132,
 9446,
 316,
 5132,
 6889,
 7594,
 5132,
 7494,
 7182,
 8985,
 3710,
 4652,
 5069,
 8985,
 5069,
 7182,
 9803,
 411,
 5069,
 6258,
 9803,
 649,
 1264,
 2181,
 6268,
 2181,
 5127,
 5447,
 5493,
 7208,
 1264,
 1642,
 5264,
 5447,
 5493,
 6268,
 1264,
 5127,
 5264,
 6201,
 6268,
 6549,
 7160,
 8480,
 6549,
 7160,
 8480,
 8220,
 8480,
 4681,
 5112,
 8117,
 5112,
 6549,
 7165,
 8117,
 5112,
 7165,
 8117,
 9694,
 4681,
 5184,
 7165,
 9694,
 5112,
 8117,
 2701,
 8007,
 815,
 3638,
 5419,
 2701,
 3638,
 552,
 4811,
 5419,
 815,
 552,
 815,
 4132,
 4811,
 5419,
 830,
 2701,
 3638,
 5419,
 552,
 3278,
 4132,
 4811,
 316,
 3390,
 7594,
 8261,
 8447,
 731,
 3203,
 3203,
 6273,
 316,
 514,
 2681,
 5804,
 7594,
 1390,
 3390,
 5804,
 731,
 1782,
 3203,
 6273,
 316,
 3203,
 3390,
 5804,
 6515,
 7594,
 9874,
 2695,
 5060,
 9013]

# 將同時間之資料作合併，完成資料前處理

In [48]:
count = []
for i in p:
    count.append(p[i])
temp = []

i = new_new_data
s = 0
for j in count:
    tmp = []
    for x in range(j):
        tmp.append(i[s])
        s+=1
    temp.append(tmp)
temp

[[166, 4103, 8715],
 [4103, 8715],
 [166, 3704, 6568, 8375, 8715],
 [166, 9406],
 [2404, 5954, 6282],
 [2404, 5954, 6282],
 [2404, 3203],
 [5132, 9446],
 [316, 5132, 6889, 7594],
 [5132, 7494],
 [7182, 8985],
 [3710, 4652, 5069, 8985],
 [5069, 7182, 9803],
 [411, 5069, 6258, 9803],
 [649, 1264, 2181, 6268],
 [2181, 5127, 5447, 5493, 7208],
 [1264, 1642, 5264, 5447, 5493, 6268],
 [1264, 5127, 5264, 6201, 6268],
 [6549, 7160, 8480],
 [6549, 7160, 8480],
 [8220, 8480],
 [4681, 5112, 8117],
 [5112, 6549, 7165, 8117],
 [5112, 7165, 8117, 9694],
 [4681, 5184, 7165, 9694],
 [5112, 8117],
 [2701, 8007],
 [815, 3638, 5419],
 [2701, 3638],
 [552, 4811, 5419],
 [815],
 [552, 815, 4132, 4811, 5419],
 [830, 2701, 3638, 5419],
 [552, 3278, 4132, 4811],
 [316, 3390, 7594, 8261, 8447],
 [731, 3203],
 [3203, 6273],
 [316, 514, 2681, 5804, 7594],
 [1390, 3390, 5804],
 [731, 1782, 3203, 6273],
 [316, 3203, 3390, 5804, 6515, 7594, 9874],
 [2695],
 [5060, 9013]]

In [49]:
data_ok = [] #轉換完成之資料
for i in temp:
    for j in i:
        data_ok.append(j)
    data_ok.append(i)

# 計算資料個數，用於後續運算使用

In [50]:
count_array = []
for i in new_data:
    count_array.append(len(i))
print(count_array)

new_index = []
for i in index:
    t = []
    for j in i:  # 1st loop
        if j not in t:   # 2nd loop
            t.append(j)
    new_index.append(t)

index_count = []
for i in new_index:
    index_count.append(len(i))
print(index_count)

count_sum = np.sum([count_array,index_count],axis=0).tolist()
print(count_sum)

[12, 8, 8, 13, 20, 8, 17, 24, 28, 3]
[4, 3, 3, 4, 4, 3, 5, 8, 7, 2]
[16, 11, 11, 17, 24, 11, 22, 32, 35, 5]

# 建立完整之資料(將同時間的交易資料拆分，用於後續計算資料個數)

In [51]:
data_ok_ok = [] #用於計算之資料
s=0
for i in count_sum:
    tmp = []
    for j in range(s,s+i):
        tmp.append(data_ok[j])
    s = s + i
    data_ok_ok.append(tmp)
data_ok_ok

[[166,
  4103,
  8715,
  [166, 4103, 8715],
  4103,
  8715,
  [4103, 8715],
  166,
  3704,
  6568,
  8375,
  8715,
  [166, 3704, 6568, 8375, 8715],
  166,
  9406,
  [166, 9406]],
 [2404,
  5954,
  6282,
  [2404, 5954, 6282],
  2404,
  5954,
  6282,
  [2404, 5954, 6282],
  2404,
  3203,
  [2404, 3203]],
 [5132,
  9446,
  [5132, 9446],
  316,
  5132,
  6889,
  7594,
  [316, 5132, 6889, 7594],
  5132,
  7494,
  [5132, 7494]],
 [7182,
  8985,
  [7182, 8985],
  3710,
  4652,
  5069,
  8985,
  [3710, 4652, 5069, 8985],
  5069,
  7182,
  9803,
  [5069, 7182, 9803],
  411,
  5069,
  6258,
  9803,
  [411, 5069, 6258, 9803]],
 [649,
  1264,
  2181,
  6268,
  [649, 1264, 2181, 6268],
  2181,
  5127,
  5447,
  5493,
  7208,
  [2181, 5127, 5447, 5493, 7208],
  1264,
  1642,
  5264,
  5447,
  5493,
  6268,
  [1264, 1642, 5264, 5447, 5493, 6268],
  1264,
  5127,
  5264,
  6201,
  6268,
  [1264, 5127, 5264, 6201, 6268]],
 [6549,
  7160,
  8480,
  [6549, 7160, 8480],
  6549,
  7160,
  8480,
  [6549, 7160, 8480],
  8220,
  8480,
  [8220, 8480]],
 [4681,
  5112,
  8117,
  [4681, 5112, 8117],
  5112,
  6549,
  7165,
  8117,
  [5112, 6549, 7165, 8117],
  5112,
  7165,
  8117,
  9694,
  [5112, 7165, 8117, 9694],
  4681,
  5184,
  7165,
  9694,
  [4681, 5184, 7165, 9694],
  5112,
  8117,
  [5112, 8117]],
 [2701,
  8007,
  [2701, 8007],
  815,
  3638,
  5419,
  [815, 3638, 5419],
  2701,
  3638,
  [2701, 3638],
  552,
  4811,
  5419,
  [552, 4811, 5419],
  815,
  [815],
  552,
  815,
  4132,
  4811,
  5419,
  [552, 815, 4132, 4811, 5419],
  830,
  2701,
  3638,
  5419,
  [830, 2701, 3638, 5419],
  552,
  3278,
  4132,
  4811,
  [552, 3278, 4132, 4811]],
 [316,
  3390,
  7594,
  8261,
  8447,
  [316, 3390, 7594, 8261, 8447],
  731,
  3203,
  [731, 3203],
  3203,
  6273,
  [3203, 6273],
  316,
  514,
  2681,
  5804,
  7594,
  [316, 514, 2681, 5804, 7594],
  1390,
  3390,
  5804,
  [1390, 3390, 5804],
  731,
  1782,
  3203,
  6273,
  [731, 1782, 3203, 6273],
  316,
  3203,
  3390,
  5804,
  6515,
  7594,
  9874,
  [316, 3203, 3390, 5804, 6515, 7594, 9874]],
 [2695, [2695], 5060, 9013, [5060, 9013]]]

# 完整資料(資料前處理完成)

In [52]:
index_ok = [] #資料矩陣
s=0
for i in index_count:
    tmp = []
    for j in range(s,s+i):
        tmp.append(temp[j])
    s = s + i
    index_ok.append(tmp)
for i in index_ok:
    print(i)

[[166, 4103, 8715], [4103, 8715], [166, 3704, 6568, 8375, 8715], [166, 9406]]
[[2404, 5954, 6282], [2404, 5954, 6282], [2404, 3203]]
[[5132, 9446], [316, 5132, 6889, 7594], [5132, 7494]]
[[7182, 8985], [3710, 4652, 5069, 8985], [5069, 7182, 9803], [411, 5069, 6258, 9803]]
[[649, 1264, 2181, 6268], [2181, 5127, 5447, 5493, 7208], [1264, 1642, 5264, 5447, 5493, 6268], [1264, 5127, 5264, 6201, 6268]]
[[6549, 7160, 8480], [6549, 7160, 8480], [8220, 8480]]
[[4681, 5112, 8117], [5112, 6549, 7165, 8117], [5112, 7165, 8117, 9694], [4681, 5184, 7165, 9694], [5112, 8117]]
[[2701, 8007], [815, 3638, 5419], [2701, 3638], [552, 4811, 5419], [815], [552, 815, 4132, 4811, 5419], [830, 2701, 3638, 5419], [552, 3278, 4132, 4811]]
[[316, 3390, 7594, 8261, 8447], [731, 3203], [3203, 6273], [316, 514, 2681, 5804, 7594], [1390, 3390, 5804], [731, 1782, 3203, 6273], [316, 3203, 3390, 5804, 6515, 7594, 9874]]
[[2695], [5060, 9013]]

# 設定min_sup

In [53]:
min_sup = eval(input("請輸入min support(0-1)："))
sup = min_sup*len(test)
sup

請輸入min support(0-1)：0.2

2.0

# 計算資料個數，將小於min_sup之資料刪除

In [54]:
init = [] #紀錄每一種資料
data = []

for i in new_data:
    tmp = list(set(i))
    data.append(tmp)
for i in data:
    for j in i:
        if(j not in init):
            init.append(j)
print(init)

[166, 4103, 6568, 8715, 8375, 3704, 9406, 5954, 3203, 2404, 6282, 9446, 7494, 6889, 7594, 5132, 316, 9803, 4652, 5069, 7182, 6258, 8985, 411, 3710, 2181, 5127, 5447, 649, 7208, 1642, 1264, 5264, 5493, 6201, 6268, 7160, 8480, 8220, 6549, 5184, 4681, 8117, 5112, 7165, 9694, 4132, 8007, 552, 5419, 4811, 2701, 3278, 815, 3638, 830, 6273, 514, 8261, 5804, 1390, 9874, 6515, 1782, 2681, 731, 3390, 8447, 5060, 9013, 2695]

In [55]:
from collections import Counter #匯入一種dict的子類別 存放資料
c = Counter()
for i in init:
    for d in new:
        if(i in d):
            c[i]+=1
print("計算index數量：") #每種資料個紀錄一次(出現次數)
for i in c:
    print(str([i])+": "+str(c[i])) #出現次數
print()

l = Counter() #另建立一個counter紀錄符合min support的資料
for i in c:
    if(c[i] >= sup): #需大於min support
        l[frozenset([i])]+=c[i] #凍結集合 無法更改之集合
print("L1:") #篩選後的資料
for i in l:
    print(str(list(i))+": "+str(l[i])) #出現次數
print()

計算index數量：
[166]: 1
[4103]: 1
[6568]: 1
[8715]: 1
[8375]: 1
[3704]: 1
[9406]: 1
[5954]: 1
[3203]: 2
[2404]: 1
[6282]: 1
[9446]: 1
[7494]: 1
[6889]: 1
[7594]: 2
[5132]: 1
[316]: 2
[9803]: 1
[4652]: 1
[5069]: 1
[7182]: 1
[6258]: 1
[8985]: 1
[411]: 2
[3710]: 1
[2181]: 1
[5127]: 1
[5447]: 1
[649]: 1
[7208]: 1
[1642]: 1
[1264]: 1
[5264]: 1
[5493]: 1
[6201]: 1
[6268]: 1
[7160]: 1
[8480]: 1
[8220]: 1
[6549]: 2
[5184]: 1
[4681]: 1
[8117]: 1
[5112]: 1
[7165]: 1
[9694]: 1
[4132]: 1
[8007]: 1
[552]: 1
[5419]: 1
[4811]: 1
[2701]: 1
[3278]: 1
[815]: 1
[3638]: 1
[830]: 1
[6273]: 1
[514]: 1
[8261]: 1
[5804]: 1
[1390]: 1
[9874]: 1
[6515]: 1
[1782]: 1
[2681]: 1
[731]: 1
[3390]: 1
[8447]: 1
[5060]: 1
[9013]: 1
[2695]: 1

L1:
[3203]: 2
[7594]: 2
[316]: 2
[411]: 2
[6549]: 2

In [56]:
L = [] #符合min_sup的元素
for i in l:
    for j in i:
        L.append(j)
i = index_ok
#刪除所有不符合min_sup的元素
n = 0
while n < len(index_ok):
    for j in i:
        for k in j:
            for h in k:
                if h not in L:
                    while(h in k):
                        k.remove(h)
    n += 1
i

[[[], [], [], []],
 [[], [], [3203]],
 [[], [316, 7594], []],
 [[], [], [], [411]],
 [[], [], [], []],
 [[6549], [6549], []],
 [[], [6549], [], [], []],
 [[], [], [], [], [], [], [], []],
 [[316, 7594], [3203], [3203], [316, 7594], [], [3203], [316, 3203, 7594]],
 [[], []]]

In [57]:
index_ok

[[[], [], [], []],
 [[], [], [3203]],
 [[], [316, 7594], []],
 [[], [], [], [411]],
 [[], [], [], []],
 [[6549], [6549], []],
 [[], [6549], [], [], []],
 [[], [], [], [], [], [], [], []],
 [[316, 7594], [3203], [3203], [316, 7594], [], [3203], [316, 3203, 7594]],
 [[], []]]

In [58]:
n = 0
while n > len(index_ok):
    for i in index_ok:
        for j in i:
            if len(j) == 0:
                i.remove(j)
                n += 1
index_ok

[[[], [], [], []],
 [[], [], [3203]],
 [[], [316, 7594], []],
 [[], [], [], [411]],
 [[], [], [], []],
 [[6549], [6549], []],
 [[], [6549], [], [], []],
 [[], [], [], [], [], [], [], []],
 [[316, 7594], [3203], [3203], [316, 7594], [], [3203], [316, 3203, 7594]],
 [[], []]]

# 完成刪除不符合min_sup之資料

In [63]:
teemp = []
for i in index_ok:
    tmp = []
    for j in i:
        if len(j) != 0:
            tmp.append(j)
    if len(tmp) > 1:
        teemp.append(tmp)
teemp

[[[6549], [6549]],
 [[316, 7594], [3203], [3203], [316, 7594], [3203], [316, 3203, 7594]]]

# 處理及列舉所有符合min_sup之交易序列

In [70]:
combinations = []
import itertools
for my_list in teemp:
    for i in range(len(my_list)):
        for combination in itertools.product(*my_list[:i+1]):
            if i == len(my_list) - 1:
#                 print([[x] for x in combination])
                combinations.append([[x] for x in combination])
            else:
#                 print(my_list[:i] + [list(combination)] + my_list[i+1:])
                combinations.append(my_list[:i] + [list(combination)] + my_list[i+1:])
combinations

[[[6549], [6549]],
 [[6549], [6549]],
 [[316], [3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[7594], [3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[316, 7594], [316, 3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[316, 7594], [7594, 3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [316, 3203, 3203],
  [316, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [7594, 3203, 3203],
  [316, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 3203, 3203, 316],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 3203, 3203, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [7594, 3203, 3203, 316],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [7594, 3203, 3203, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [316, 3203, 3203, 316, 3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [316, 3203, 3203, 7594, 3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [7594, 3203, 3203, 316, 3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [7594, 3203, 3203, 7594, 3203],
  [316, 3203, 7594]],
 [[316], [3203], [3203], [316], [3203], [316]],
 [[316], [3203], [3203], [316], [3203], [3203]],
 [[316], [3203], [3203], [316], [3203], [7594]],
 [[316], [3203], [3203], [7594], [3203], [316]],
 [[316], [3203], [3203], [7594], [3203], [3203]],
 [[316], [3203], [3203], [7594], [3203], [7594]],
 [[7594], [3203], [3203], [316], [3203], [316]],
 [[7594], [3203], [3203], [316], [3203], [3203]],
 [[7594], [3203], [3203], [316], [3203], [7594]],
 [[7594], [3203], [3203], [7594], [3203], [316]],
 [[7594], [3203], [3203], [7594], [3203], [3203]],
 [[7594], [3203], [3203], [7594], [3203], [7594]]]

In [73]:
combinations_unique = [] #完成之資料序列
for i in combinations:         # 1st loop
    if i not in combinations_unique and len(i) > 1:   # 2nd loop
        combinations_unique.append(i)
combinations_unique

[[[6549], [6549]],
 [[316], [3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[7594], [3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[316, 7594], [316, 3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[316, 7594], [7594, 3203], [3203], [316, 7594], [3203], [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [316, 3203, 3203],
  [316, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [7594, 3203, 3203],
  [316, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 3203, 3203, 316],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 3203, 3203, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [7594, 3203, 3203, 316],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [7594, 3203, 3203, 7594],
  [3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [316, 3203, 3203, 316, 3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [316, 3203, 3203, 7594, 3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [7594, 3203, 3203, 316, 3203],
  [316, 3203, 7594]],
 [[316, 7594],
  [3203],
  [3203],
  [316, 7594],
  [7594, 3203, 3203, 7594, 3203],
  [316, 3203, 7594]],
 [[316], [3203], [3203], [316], [3203], [316]],
 [[316], [3203], [3203], [316], [3203], [3203]],
 [[316], [3203], [3203], [316], [3203], [7594]],
 [[316], [3203], [3203], [7594], [3203], [316]],
 [[316], [3203], [3203], [7594], [3203], [3203]],
 [[316], [3203], [3203], [7594], [3203], [7594]],
 [[7594], [3203], [3203], [316], [3203], [316]],
 [[7594], [3203], [3203], [316], [3203], [3203]],
 [[7594], [3203], [3203], [316], [3203], [7594]],
 [[7594], [3203], [3203], [7594], [3203], [316]],
 [[7594], [3203], [3203], [7594], [3203], [3203]],
 [[7594], [3203], [3203], [7594], [3203], [7594]]]

In [259]:
path = 'output_small_sample.txt'
f = open(path, 'w')
f.write('符合min_sup之sequential pattern：\n')
for i in teemp:
    f.write(str(i))
    f.write('\n')
f.write('\n')
f.write('\n')
f.write('\n')
f.write('其子集合(排列組合)：\n')
for i in combinations_unique:
    f.write(str(i))
    f.write('\n')
f.close()

# 計算符合min_sup之sequential pattern的support

In [252]:
from collections import Counter #匯入一種dict的子類別 存放資料
c = Counter()
init = []
for i in teemp:
    for j in i:
        init.append(j)
for i in init:
    for d in teemp:
        if(i in d):
            c[i[0]]+=1
        if(i not in d):
            for s in d:
                if(i in s):
                    c[i[0]]+=1
                    break
print("C1:") #每種資料個紀錄一次(出現次數)
for i in c:
    print(str([i])+": "+str(c[i])) #出現次數
print()

l = Counter() #另建立一個counter紀錄符合min support的資料
for i in c:
    if(c[i] >= sup): #需大於min support
        l[frozenset([i])]+=c[i] #凍結集合 無法更改之集合
print("L1:") #篩選後的資料
for i in l:
    print(str(list(i))+": "+str(l[i])) #出現次數
print()

all =[] #用於記錄除了單元組合以外，2元素組合以上符合min support的資料組合
pl = l #用於紀錄最大資料組合
pos = 1 #用於紀錄最大資料組合之回合數
for count in range (2,1000): #迭代次數/回合數(round)
    nc = set() #紀錄資料組合
    temp = list(l) #暫存上一步經過篩選後的集合
    for i in range(0,len(temp)): #將L1中的元素排列組合 組合成新的集合
        for j in range(i+1,len(temp)):
            t = temp[i].union(temp[j])
            if(len(t) == count):
                nc.add(temp[i].union(temp[j])) #連結
    nc = list(nc)
    c = Counter()
    for i in nc:
        c[i] = 0 #INIT集合
        for j in data:
            temp = set(j)
            if(i.issubset(temp)):
                c[i]+=1
    print("C"+str(count)+":") #第幾次的組合
    for i in c:
        print(str(list(i))+": "+str(c[i])) #顯示每一組資料組合的出現頻率
    print()
    
    l = Counter() #紀錄篩選後符合min support的組合
    for i in c:
        if(c[i] >= sup):
            l[i]+=c[i]
    print("L"+str(count)+":") #第幾次篩選後的組合
    for i in l:
        print(str(list(i))+": "+str(l[i])) #print篩選後的組合
    all.append(l)
    print()
    if(len(l) == 0): #停止點(若篩選後的組合數為0代表後續組合無法搭於min support)
        break
    pl = l #最多元素之組合
    pos = count #第幾回合(round)
print("The Max combination: ") #print最大組合之資料
print("L"+str(pos)+":")
for i in pl:
    print(str(list(i))+": "+str(pl[i]))
print()

C1:
[6549]: 2
[316]: 3
[3203]: 3

L1:
[6549]: 2
[316]: 3
[3203]: 3

C2:
[3203, 316]: 1
[316, 6549]: 0
[3203, 6549]: 0

L2:

The Max combination:
L1:
[6549]: 2
[316]: 3
[3203]: 3